config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, :path => "", :path_names => {
      :sign_in      => 'login',
      :sign_out     => 'logout',
      :password     => 'secret',
      :confirmation => 'verification',
      :unlock       => 'unlock',
      :registration => 'register',
      :sign_up      => 'new' }
  resources :requests
  resources :comments
  resources :rooms
  resources :locals
  resources :songs
  resources :reserves
  resources :events
  resources :products

  get 'users', to: 'users#index', as: 'users'
  get 'reservesClient', to: 'reserves#newClient', as: 'reCLient'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root to: 'home#index', as: 'home'
  get 'reserves', to: 'reserves#new'

  get 'comentarios/:id/', to: 'comments#index_comments_x_rooms', as: 'comentarios'

  get 'pagesusers/reservasala' 
  get 'pagesusers/solicitacancion'
  get 'pagesusers/userregistration'
  get 'pagesusers/solicitapedido'
  get 'cliente',  to: 'pagesusers#index', as: 'cliente'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  Nombre_de_evento :string
#  Fecha_y_hora     :datetime
#  Capacidad_maxima :integer
#  Descripcion      :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#


class Event < ApplicationRecord
    belongs_to :local

    #Validamos los datos del evento que se agregue
    # mostramos el mensaje de error con message
    validates :Nombre_de_evento , confirmation: true, presence: { message: " dato obligatorio"}
    validates :Capacidad_maxima , :numericality => { :only_integer => true }
    validates :Descripcion , confirmation: true, presence: { message: " dato obligatorio"}

    validates :local_id , presence: true , confirmation: true
end

app/controllers/events_controller.rb
class EventsController < KaraokeController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    authorize Event
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize Event
  end

  # GET /events/new
  def new
    authorize Event
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize Event
  end

  # POST /events
  # POST /events.json
  def create
    authorize Event

    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize Event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize Event

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:Nombre_de_evento, :Fecha_y_hora, :Capacidad_maxima, :Descripcion, :local_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= bootstrap_form_for(@event) do |f| %>
    <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "Campo con informacion incorrecta") %> no se puede guardar este evento:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.text_field :Nombre_de_evento, label: "Nombre:" %>
    <%= f.datetime_select :Fecha_y_hora, label: "Fecha y Hora:" %>
    <%= f.number_field :Capacidad_maxima, label: "Capacidad Maxima:" %>
    <%= f.text_field :Descripcion, label: "Descripcion:" %>
    <%= f.collection_select :local_id, Local.all, :id, :nombre, label: "Local:", :prompt => true %>
    <%= f.submit "Guardar Cambios", class: "btn btn-success" %>
    <%= link_to 'Cancelar', locals_path, class:"btn btn-danger"  %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Cabezera -->

 <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Lista de Eventos Registrados</h3>
      <div class="pull-right">
          <%= link_to(new_event_path) do %>
              <p data-placement="top" data-toggle="tooltip" title="New">
                <button class="btn btn-sm btn-primary btn-create" data-title="New" data-toggle="modal">
                  <span class="glyphicon glyphicon-plus"></span> Nuevo Evento
                </button>
              </p>
          <% end %>
          <span id="notice" class="alert"><%= notice %></span>
      </div>
    </div>

<!-- Fin Cabezera -->
<!-- <h1>Events</h1> -->
   <div class="box-body table-responsive no-padding">
    <table class="table table-hover table-bordered">
     <thead>
      <tr>
       <th>#</th>
       <th>Nombre de evento</th>
       <th>Fecha y hora</th>
       <th>Capacidad maxima</th>
       <th>Descripcion</th>
       <th>Local</th>
       <th>Edit</th>
       <th>Delete</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     
    <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.Nombre_de_evento %></td>
        <td><%= event.Fecha_y_hora %></td>
        <td><%= event.Capacidad_maxima %></td>
        <td><%= event.Descripcion %></td>
        <td><%= event.local.nombre %></td>
        <td align="center">
              <%= link_to(edit_event_path(event)) do %>
                    <p data-placement="top" data-toggle="tooltip" title="Edit">
                      <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" >
                        <span class="glyphicon glyphicon-pencil"></span>
                      </button>
                    </p>
                <% end %>
            </td>
            <td align="center">
                <%= link_to(event, method: :delete, data: { confirm: 'Are you sure?' } ) do %>
                    <p data-placement="top" data-toggle="tooltip" title="Delete" >
                      <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" >
                        <span class="glyphicon glyphicon-trash"></span>
                      </button>
                    </p>
                <% end %>
            </td>
        </tr>
       <% end %>
      </tbody>
    </table>
   </div> 
   
  </div> 
    <br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre de evento:</strong>
  <%= @event.Nombre_de_evento %>
</p>

<p>
  <strong>Fecha y hora:</strong>
  <%= @event.Fecha_y_hora %>
</p>

<p>
  <strong>Capacidad maxima:</strong>
  <%= @event.Capacidad_maxima %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @event.Descripcion %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>