config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, :path => "", :path_names => {
      :sign_in      => 'login',
      :sign_out     => 'logout',
      :password     => 'secret',
      :confirmation => 'verification',
      :unlock       => 'unlock',
      :registration => 'register',
      :sign_up      => 'new' }
  resources :requests
  resources :comments
  resources :rooms
  resources :locals
  resources :songs
  resources :reserves
  resources :events
  resources :products

  get 'users', to: 'users#index', as: 'users'
  get 'reservesClient', to: 'reserves#newClient', as: 'reCLient'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root to: 'home#index', as: 'home'
  get 'reserves', to: 'reserves#new'

  get 'comentarios/:id/', to: 'comments#index_comments_x_rooms', as: 'comentarios'

  get 'pagesusers/reservasala' 
  get 'pagesusers/solicitacancion'
  get 'pagesusers/userregistration'
  get 'pagesusers/solicitapedido'
  get 'cliente',  to: 'pagesusers#index', as: 'cliente'

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Request < ApplicationRecord
  belongs_to :user
end

app/controllers/requests_controller.rb
class RequestsController < KaraokeController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    respond_to do |format|
      if @request.save
        session[:id_pedido] = @request.id

        format.html { redirect_to @request, notice: 'El Pedido ha sido creado.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'El pedido ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'El Pedido ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:user_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= bootstrap_form_for(@request) do |f| %>
    <% if request.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(request.errors.count, "error") %> prohibited this reserf from being saved:</h2>

          <ul>
            <% request.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.collection_select :user_id, User.where(:id => current_user.id).all, :id, :email, :disabled => true, label: "Usuario:" %>

    <%= f.submit 'Guardar', :class => 'btn btn-primary'%>

    <% if current_user.role == 'admin' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    reserves_path, :class => 'btn btn-default' %>
    <% end %>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class="box box-primary">
  <div class="box-header">
    <h3 class="box-title">Listar Reservas</h3>
    <div class="pull-right">
      <%= link_to(new_request_path) do %>
          <p data-placement="top" data-toggle="tooltip" title="New">
            <button class="btn btn-sm btn-primary btn-create" data-title="New" data-toggle="modal">
              <span class="glyphicon glyphicon-plus"></span> Nueva Pedido
            </button>
          </p>
      <% end %>
      <span id="notice" class="alert"><%= notice %></span>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table id='request' class="display" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>#</th>
        <th>User</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      </thead>

      <tbody>
      <% @requests.each do |request| %>
          <tr>
            <td><%= request.id %></td>
            <td><%= current_user.nombre %> <%= current_user.apellido_paterno %></td>
            <td align="center">
              <%= link_to(edit_request_path(request)) do %>
                  <p data-placement="top" data-toggle="tooltip" title="Edit">
                    <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" >
                      <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                  </p>
              <% end %>
            </td>
            <td align="center">
              <%= link_to(request, method: :delete ) do %>
                  <p data-placement="top" data-toggle="tooltip" title="Delete" >
                    <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" >
                      <span class="glyphicon glyphicon-trash"></span>
                    </button>
                  </p>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @request.user.nombre %> <%= @request.user.apellido_paterno %> <%= @request.user.apellido_materno %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>