config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, :path => "", :path_names => {
      :sign_in      => 'login',
      :sign_out     => 'logout',
      :password     => 'secret',
      :confirmation => 'verification',
      :unlock       => 'unlock',
      :registration => 'register',
      :sign_up      => 'new' }
  resources :requests
  resources :comments
  resources :rooms
  resources :locals
  resources :songs
  resources :reserves
  resources :events
  resources :products

  get 'users', to: 'users#index', as: 'users'
  get 'reservesClient', to: 'reserves#newClient', as: 'reCLient'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root to: 'home#index', as: 'home'
  get 'reserves', to: 'reserves#new'

  get 'comentarios/:id/', to: 'comments#index_comments_x_rooms', as: 'comentarios'

  get 'pagesusers/reservasala' 
  get 'pagesusers/solicitacancion'
  get 'pagesusers/userregistration'
  get 'pagesusers/solicitapedido'
  get 'cliente',  to: 'pagesusers#index', as: 'cliente'

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id          :integer          not null, primary key
#  nombre      :string
#  capacidad   :integer
#  descripcion :text
#  local_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#



class Room < ApplicationRecord
  belongs_to :local
  has_many :comment
	has_many :reserves

 	#Validaciones de Presencia
	validates :nombre , presence: true , confirmation: true

	validates :capacidad, length: { in: 1..1 , message: "Debe ser menor a 10 "}
	validates :capacidad, numericality: { only_integer: true }

	validates :capacidad , presence: true , confirmation: true
	validates :local_id , presence: true , confirmation: true

end

app/controllers/rooms_controller.rb
class RoomsController < KaraokeController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show

  end

  # GET /rooms/new
  def new
    authorize Room
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    authorize Room
  end

  # POST /rooms
  # POST /rooms.json
  def create
    authorize Room

    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    authorize Room

    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    authorize Room

    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:nombre, :capacidad, :descripcion, :local_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= bootstrap_form_for(@room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "Campo con informacion incorrecta") %> no se puede guardar esta sala:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :nombre, label: "Nombre:" %>
  <%= f.text_field :capacidad, label: "Capacidad:" %>
  <%= f.text_field :descripcion, label: "Descripcion:" %>
  <%= f.collection_select :local_id, Local.all, :id, :nombre, label: "Local:", :prompt => true %>
  <%= f.submit "Guardar Cambios", class: "btn btn-success" %>
  <%= link_to 'Cancelar', locals_path, class:"btn btn-danger"  %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Salas</h3>
      <div class="pull-right">
          <%= link_to(new_room_path) do %>
              <p data-placement="top" data-toggle="tooltip" title="New">
                <button class="btn btn-sm btn-primary btn-create" data-title="New" data-toggle="modal">
                  <span class="glyphicon glyphicon-plus"></span> Nueva Sala
                </button>
              </p>
          <% end %>
          <span id="notice" class="alert"><%= notice %></span>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">

     <% if current_user.role == 'admin' %>
      <table id='rooms' class="display" cellspacing="0" width="100%">
        <thead>
          <tr >
            <th>#</th>
            <th>Nombre</th>
            <th>Capacidad</th>
            <th>Descripción</th>
            <th>Local</th>
            <th>Editar</th>
            <th>Eliminar</th>
          </tr>
        </thead>

        <tbody>
        <% @rooms.each do |room| %>
            <tr>
              <td><%= room.id %></td>
              <td><%= room.nombre %></td>
              <td><%= room.capacidad %></td>
              <td><%= room.descripcion %></td>
              <td><%= room.local.nombre %></td>
              <td align="center">
                <%= link_to(edit_room_path(room)) do %>
                    <p data-placement="top" data-toggle="tooltip" title="Edit">
                      <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" >
                        <span class="glyphicon glyphicon-pencil"></span>
                      </button>
                    </p>
                <% end %>
              </td>
              <td align="center">
                <%= link_to(room, method: :delete ) do %>
                    <p data-placement="top" data-toggle="tooltip" title="Delete" >
                      <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" >
                        <span class="glyphicon glyphicon-trash"></span>
                      </button>
                    </p>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <% else %>
          <table id='rooms' class="display" cellspacing="0" width="100%">
            <thead>
            <tr >
              <th>#</th>
              <th>Nombre</th>
              <th>Capacidad</th>
              <th>Descripción</th>
              <th>Local</th>
              <th>Ver comentarios</th>
            </tr>
            </thead>

            <tbody>
            <% @rooms.each do |room| %>
                <tr>
                  <td><%= room.id %></td>
                  <td><%= room.nombre %></td>
                  <td><%= room.capacidad %></td>
                  <td><%= room.descripcion %></td>
                  <td><%= room.local.nombre %></td>
                  <td align="center">
                    <%= link_to(comentarios_path(room)) do %>
                        <p data-placement="top" data-toggle="tooltip" title="Edit">
                          <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" >
                            <span class="glyphicon glyphicon-pencil"></span>
                          </button>
                        </p>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% end %>
    </div>
    <!-- /.box-body -->
  </div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @room.nombre %>
</p>

<p>
  <strong>Capacidad:</strong>
  <%= @room.capacidad %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @room.descripcion %>
</p>

<p>
  <strong>Local:</strong>
  <%= @room.local.nombre %>
</p>

<%= link_to 'Editar', edit_room_path(@room) %> |
<%= link_to 'Regresar', rooms_path %>